SELECT [CustomerKey]
      ,[GeographyKey]
      ,[FirstName]
      ,[LastName]
      ,[MaritalStatus]
      ,[Gender]
      ,[YearlyIncome]
      ,[TotalChildren]
      ,[NumberChildrenAtHome]
      ,[EnglishEducation]
      ,[SpanishEducation]
      ,[FrenchEducation]
      ,[EnglishOccupation]
      ,[SpanishOccupation]
      ,[FrenchOccupation]
      ,[HouseOwnerFlag]
      ,[NumberCarsOwned]
  FROM [AdventureWorksDW2025].[dbo].[DimCustomer]
