SELECT [ProductKey]
      ,[OrderDateKey]
      ,[DueDateKey]
      ,[ShipDateKey]
      ,[CustomerKey]
      ,[SalesTerritoryKey]
      ,[OrderQuantity]
      ,[UnitPrice]
      ,[TotalProductCost]
      ,[SalesAmount]
  FROM [AdventureWorksDW2025].[dbo].[FactInternetSales]
